export { createAnalyzer, verdictOf } from './analyzer.js';
export type { Analyzer, AnalyzerOptions, Component } from './analyzer.js';
export { parseArgs } from './args.js';
export type { CliArgs } from './args.js';
export { runCli, USAGE } from './cli.js';
export type { CliContext, OutputStream } from './cli.js';
export { PropFlowError } from './errors.js';
export { analyseProps } from './prop-flow.js';
export type { AnalyseOptions } from './prop-flow.js';
export { formatJson, formatText } from './report.js';
export { discoverTsconfig, readTsConfig } from './tsconfig.js';
export type { OptionalProp, PropAnalysis, PropReport, Report, Site, SiteKind, Verdict } from './types.js';
export { loadTypeScript } from './typescript-api.js';
export type { TypeScriptApi } from './typescript-api.js';
